export const items = [
    {
      image: "images/Elie.jpeg",
      title: "Irakoze Elie",
      subtitle: "Software Engineer",
      handle: "@iraelie",
      borderColor: "#4F46E5",
      gradient: "linear-gradient(145deg,#4F46E5,#000)",
      url: "https://www.linkedin.com/in/niyubwayo-irakoze-elie-14b003284/",
    },
    {
      image: "images/Jesse.jpeg",
      title: "Jesse Raura",
      subtitle: "Speech",
      handle: "@jesseraura",
      borderColor: "#10B981",
      gradient: "linear-gradient(210deg,#10B981,#000)",
      url: "https://www.instagram.com/_ma.g.ic/",
    },
    {
      image: "images/Prince.jpeg",
      title: "Nkubana Prince",
      subtitle: "Scheduler",
      handle: "@princenkuba",
      borderColor: "#F59E0B",
      gradient: "linear-gradient(165deg,#F59E0B,#000)",
      url: "https://www.linkedin.com/in/mico-prince-749b5a324/",
    },
    {
      image: "images/Gift.jpeg",
      title: "Providence Gift",
      subtitle: "Kiyongozi",
      handle: "@giftprovi",
      borderColor: "#EF4444",
      gradient: "linear-gradient(195deg,#EF4444,#000)",
      url: "https://www.instagram.com/gift_wa_s.o/profilecard/?igsh=bXp3YXl4M2d0MTE3",
    },
    {
      image: "images/Gisa.jpeg",
      title: "Gisa Dan",
      subtitle: "Researcher",
      handle: "@gisa",
      borderColor: "#8B5CF6",
      gradient: "linear-gradient(225deg,#8B5CF6,#000)",
      url: "https://www.instagram.com/gisa_klay/",
    },
    {
      image: "images/David.jpeg",
      title: "David",
      subtitle: "Video Editor",
      handle: "@david",
      borderColor: "#06B6D4",
      gradient: "linear-gradient(135deg,#06B6D4,#000)",
      url: "https://www.instagram.com/david1ne_/",
    },
  ];