export const items = [
    {
      image: "images/Elie.jpeg",
      title: "Irakoze Elie",
      subtitle: "Software Engineer",
      handle: "@iraelie",
      borderColor: "#4F46E5",
      gradient: "linear-gradient(145deg,#4F46E5,#000)",
      url: "https://www.linkedin.com/in/niyubwayo-irakoze-elie-14b003284/",
    },
    {
      image: "images/Jesse.jpeg",
      title: "Jesse Raura",
      subtitle: "Speech",
      handle: "@jesseraura",
      borderColor: "#10B981",
      gradient: "linear-gradient(210deg,#10B981,#000)",
      url: "https://linkedin.com/in/",
    },
    {
      image: "images/Prince.jpeg",
      title: "Nkubana Prince",
      subtitle: "Scheduler",
      handle: "@princenkuba",
      borderColor: "#F59E0B",
      gradient: "linear-gradient(165deg,#F59E0B,#000)",
      url: "https://dribbble.com/",
    },
    {
      image: "https://i.pravatar.cc/300?img=16",
      title: "Providence Gift",
      subtitle: "Kiyongozi",
      handle: "@giftprovi",
      borderColor: "#EF4444",
      gradient: "linear-gradient(195deg,#EF4444,#000)",
      url: "https://kaggle.com/",
    },
    {
      image: "https://i.pravatar.cc/300?img=25",
      title: "Gisa Dan",
      subtitle: "Researcher",
      handle: "@gisa",
      borderColor: "#8B5CF6",
      gradient: "linear-gradient(225deg,#8B5CF6,#000)",
      url: "https://github.com/",
    },
    {
      image: "https://i.pravatar.cc/300?img=60",
      title: "David",
      subtitle: "Video Editor",
      handle: "@david",
      borderColor: "#06B6D4",
      gradient: "linear-gradient(135deg,#06B6D4,#000)",
      url: "https://aws.amazon.com/",
    },
  ];